formatting

diff --git a/ebs b/ebs
--- a/ebs
+++ b/ebs
@@ -50,16 +50,17 @@ attach() {
 	ATTACH_DEVICE=$(echo ${JSON_PARAMS} | jq -r '.attachDevice')
 	MOUNT_DEVICE=$(echo ${JSON_PARAMS} | jq -r '.mountDevice')
 
-    INSTANCE_ID=$(aws ec2 describe-instances --region $REGION --filters "Name=private-dns-name,Values=${NODE_NAME}.ec2.internal" | jq -r '.Reservations[].Instances[].InstanceId')
-    OUTPUT=$(aws ec2 attach-volume --region $REGION --volume-id "$VOLUMEID" --instance-id "$INSTANCE_ID" --device "$ATTACH_DEVICE")
+  INSTANCE_ID=$(aws ec2 describe-instances --region $REGION --filters "Name=private-dns-name,Values=${NODE_NAME}.ec2.internal" | jq -r '.Reservations[].Instances[].InstanceId')
+  OUTPUT=$(aws ec2 attach-volume --region $REGION --volume-id "$VOLUMEID" --instance-id "$INSTANCE_ID" --device "$ATTACH_DEVICE")
+
 	if [ $? -ne 0 ]; then
-	    debug "attach $OUTPUT"
+    debug "attach $OUTPUT"
 		err "{ \"status\": \"Failure\", \"message\": \"Error mounting volume $VOLUMEID onto node/instance ${NODE_NAME}/${INSTANCE_ID}\"}"
 		exit 1
+  else
+  	log "{\"status\": \"Success\", \"device\":\"${MOUNT_DEVICE}\"}"
+	  exit 0
 	fi
-
-	log "{\"status\": \"Success\", \"device\":\"${MOUNT_DEVICE}\"}"
-	exit 0
 }
 
 #called on master periodically after calling attach()
@@ -69,35 +70,35 @@ isattached() {
 	NODE_NAME=$2
 	VOLUMEID=$(echo ${JSON_PARAMS} | jq -r '.volumeID')
 
-    INSTANCE_ID=$(aws ec2 describe-instances --region $REGION --filters "Name=private-dns-name,Values=${NODE_NAME}.ec2.internal" --query 'Reservations[*].Instances[*].InstanceId'|jq -r .[0][0])
+  INSTANCE_ID=$(aws ec2 describe-instances --region $REGION --filters "Name=private-dns-name,Values=${NODE_NAME}.ec2.internal" --query 'Reservations[*].Instances[*].InstanceId'|jq -r .[0][0])
+  ATTACH_STATUS=$(aws ec2 describe-volumes --region $REGION --volume-ids "$VOLUMEID" | jq -r '.Volumes[].Attachments[].InstanceId')
 
-    ATTACH_STATUS=$(aws ec2 describe-volumes --region $REGION --volume-ids "$VOLUMEID" | jq -r '.Volumes[].Attachments[].InstanceId')
-    if [ "$ATTACH_STATUS" == "$INSTANCE_ID" ]; then
-    	log "{\"status\": \"Success\", \"message\": \"Volume $VOLUMEID is attached to $NODE_NAME\", \"attached\":true}"
-	    exit 0
-    fi
-
-	err "{\"status\": \"Failure\", \"message\": \"Volume $VOLUMEID is not attached to $NODE_NAME\", \"attached\":false}"
-	exit 1
+  if [ "$ATTACH_STATUS" == "$INSTANCE_ID" ]; then
+    log "{\"status\": \"Success\", \"message\": \"Volume $VOLUMEID is attached to $NODE_NAME\", \"attached\":true}"
+    exit 0
+  else
+  	err "{\"status\": \"Failure\", \"message\": \"Volume $VOLUMEID is not attached to $NODE_NAME\", \"attached\":false}"
+	  exit 1
+  fi
 }
 
 #called on node, DEVICE comes from attach()
 waitforattach() {
 	debug "waitforattach $@"
-    DEVICE=$1
+  DEVICE=$1
 	JSON_PARAMS=$2
 	VOLUMEID=$(echo ${JSON_PARAMS} | jq -r '.volumeID')
 
-    end=$((SECONDS+600))
-    while [ $SECONDS -lt $end ]; do
-        if [ -b "$DEVICE" ] ; then
-            log "{\"status\": \"Success\", \"device\":\"${DEVICE}\"}"
-            exit 0
-        fi
-    done
+  end=$((SECONDS+600))
+  while [ $SECONDS -lt $end ]; do
+    if [ -b "$DEVICE" ] ; then
+      log "{\"status\": \"Success\", \"device\":\"${DEVICE}\"}"
+      exit 0
+    fi
+  done
 
-    err "{ \"status\": \"Failure\", \"message\": \"Volume ${VOLUMEID} not attached to device ${DEVICE}\" \"}"
-    exit 1
+  err "{ \"status\": \"Failure\", \"message\": \"Volume ${VOLUMEID} not attached to device ${DEVICE}\" \"}"
+  exit 1
 }
 
 #called on node, DEVICE comes from attach()
@@ -129,14 +130,15 @@ mountdevice() {
 	fi
 
 	mkdir -p ${MNTPATH} &> /dev/null
-
 	mount ${DEVICE} ${MNTPATH} &> /dev/null
+
 	if [ $? -ne 0 ]; then
 		err "{ \"status\": \"Failure\", \"message\": \"Failed to mount device ${DEVICE} at ${MNTPATH}\"}"
 		exit 1
+  else
+  	log "{\"status\": \"Success\"}"
+	  exit 0
 	fi
-	log "{\"status\": \"Success\"}"
-	exit 0
 }
 
 #called on node
@@ -155,40 +157,43 @@ unmountdevice() {
 	fi
 
 	umount ${MNTPATH} &> /dev/null
+
 	if [ $? -ne 0 ]; then
 		err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
 		exit 1
+  else
+  	log "{\"status\": \"Success\"}"
+	  exit 0
 	fi
-
-	log "{\"status\": \"Success\"}"
-	exit 0
 }
 
 #called on master
 detach() {
 	debug "detach $@"
-#	JSON_PARAMS=$1, should really be same as attach
+  #JSON_PARAMS=$1, should really be same as attach
 	PV_NAME=$1
 	NODE_NAME=$2
 	#hack - make sure PV_NAME is also the VOLUMEID
 	VOLUMEID=$PV_NAME
 
-    #don't detach is state is available
-    STATE=$(aws ec2 describe-volumes --region $REGION --volume-ids "$VOLUMEID" | jq -r '.Volumes[].State')
-    if [ "$STATE" == "available" ]; then
-        log "{\"status\": \"Success\", \"message\": \"Volume "$VOLUMEID" state is $STATE\"}"
-	    exit 0
-    fi
+  #don't detach if state is available
+  STATE=$(aws ec2 describe-volumes --region $REGION --volume-ids "$VOLUMEID" | jq -r '.Volumes[].State')
+  if [ "$STATE" == "available" ]; then
+    log "{\"status\": \"Success\", \"message\": \"Volume "$VOLUMEID" state is $STATE\"}"
+    exit 0
+  fi
 
-    OUTPUT=$(aws ec2 detach-volume --region $REGION --volume-id "$VOLUMEID")
-    if [ $? -ne 0 ]; then
-        debug "detach" "$OUTPUT"
-        err "{\"status\": \"Failure\", \"message\": \"Error detaching volume "$VOLUMEID" from $NODE_NAME\"}"
-        exit 1
-    fi
+  OUTPUT=$(aws ec2 detach-volume --region $REGION --volume-id "$VOLUMEID")
 
-	log "{\"status\": \"Success\", \"message\": \"Volume $VOLUMEID detached from $NODE_NAME\"}"
-	exit 0
+  if [ $? -ne 0 ]; then
+    debug "detach" "$OUTPUT"
+    err "{\"status\": \"Failure\", \"message\": \"Error detaching volume "$VOLUMEID" from $NODE_NAME\"}"
+    exit 1
+  else
+	  log "{\"status\": \"Success\", \"message\": \"Volume $VOLUMEID detached from $NODE_NAME\"}"
+  	exit 0
+  fi
+
 }
 
 getvolumename() {
@@ -225,8 +230,8 @@ case "$op" in
 		waitforattach $*
 		;;
 	isattached)
-        isattached $*
-        ;;
+    isattached $*
+    ;;
 	mountdevice)
 		mountdevice $*
 		;;
@@ -234,8 +239,8 @@ case "$op" in
 		unmountdevice $*
 		;;
 	*)
-        log "{ \"status\": \"Not supported\" }"
-        exit 0
+    log "{ \"status\": \"Not supported\" }"
+    exit 0
 esac
 
 exit 1
